version: 2
jobs:
  build:
    docker:
      - image: springcloud/pipeline-base
    environment:
      _JAVA_OPTIONS: "-Xms512m -Xmx768m"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx768m -XX:+HeapDumpOnOutOfMemoryError" -Dorg.gradle.daemon=false'
      TERM: dumb
    branches:
      ignore:
        - gh-pages # list of branches to ignore
    resource_class: large
    steps:
      - checkout
      - run:
          name: "Running build"
          command: ./mvnw -s .settings.xml clean org.jacoco:jacoco-maven-plugin:prepare-agent install -U -Pdocs,integration,sonar -nsu --batch-mode -Dsurefire.rerunFailingTestsCount=2 -Dmaven.test.redirectTestOutputToFile=true -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
